var places = [
      'Centerville',
      'Fairview',
      'Franklin',
      'Midway',
      'Fairfield',
      'Pleasant Valley',
      'Troy',
      'Liberty',
      'Union',
      'Springfield',
      'Clinton',
      'Madison',
      'Clayton',
      'Marion',
      'Salem',
      'Splott',
      'Bufflers Holt',
      'Warninglid',
      'Fingringhoe',
      'Snodland',
      'Ventongimps',
      'Grimness',
      'Bumpass',
      'Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch',
      'Humptulips',
      'Humansville',
      'Cheesequake',
      'Oaxaca',
      'Worcestershire',
      'Bloemfontein',
      'Mumbai',
      'Dehli',
      'Bangalor',
      'Jaipur',
      'Komkhulu',
      'Bergsig',
      'Pretoria',
      'San José',
      'San Antonio',
      'Santa Maria',
      'Santa Rosa',
      'San Pedro',
      'San Juan',
      'San Francisco',
      'Mikhaylovka',
      'Hoseynabad',
      'Ivanovka',
      'Ojo de Agua',
      'Gradina',
      'Aleksandrovka',
      'Buenavista',
      'La Esperanza'
    ],
    total = places.length - 1;

module.exports = function() {
  var idx = Math.round( Math.random() * total );
  return places[idx];
};


